apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-servidor-php
  labels:
    app: php
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      name: pod-servidor-php
      labels:
        app: php
        service: web
    spec:
      containers:
      - image: firex20/php-fpm
        name: contenedor-servidor-php
        ports:
        - name: php
          containerPort: 9000
