apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-servidor-mensajeria
  labels:
    app: mensajeria
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mensajeria
  template:
    metadata:
      name: pod-servidor-mensajeria
      labels:
        app: mensajeria
        service: web
    spec:
      containers:
      - image: nginx
        name: contenedor-servidor-mensajeria
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: web-dir
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: web-dir
        hostPath:
          path: /web-data
      - name: nginx-config
        configMap:
          name: nginx-config
