apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-servidor-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: pod-servidor-web
      labels:
        app: nginx
        service: web
    spec:
      containers:
        - image: firex20/pagina_web
          name: contenedor-servidor-web