apiVersion: v1
kind: Service
metadata:
  name: mensajeria-php
spec:
  type: NodePort
  ports:
  - name: service-http
    port: 80
    targetPort: http
  - name: service-php
    port: 8080
    targetPort: php
  selector:
    app: mensajeria-php